
export const AIResponseFormat = `
      interface Feedback {
      overallScore: number; //max 100
      ATS: {
        score: number; //how close it is to being made by an AI
        tips: {
          type: "good" | "improve";
          tip: string; //give 3-4 tips
        }[];
      };
      toneAndStyle: {
        score: number; //max 100
        tips: {
          type: "good" | "improve";
          tip: string; //make it a short "title" for the actual explanation
          explanation: string; //explain in detail here
        }[]; //give 3-4 tips
      };
      content: {
        score: number; //max 100
        tips: {
          type: "good" | "improve";
          tip: string; //make it a short "title" for the actual explanation
          explanation: string; //explain in detail here
        }[]; //give 3-4 tips
      };
      structure: {
        score: number; //max 100
        tips: {
          type: "good" | "improve";
          tip: string; //make it a short "title" for the actual explanation
          explanation: string; //explain in detail here
        }[]; //give 3-4 tips
      };;
    }`;

export const prepareInstructions = ({
                                        content
                                    }: {
    content: string;
}) =>
    `You are an expert AI-Content Authenticity Analyzer specializing in detecting whether a given text is written by a human or AI. Your task is to deeply analyze the writing style, coherence, patterns, and language characteristics to determine the likelihood of AI involvement.

Your analysis must include:
- Linguistic patterns
- Repetition, coherence, and flow
- Sentence structure complexity
- Predictability and uniformity
- Emotional depth and originality
- Over-optimization, robotic tone, or “ChatGPT-like” patterns
- Plagiarism-like generic phrasing often generated by AI
- Any red flags indicating AI rewriting or paraphrasing

You will receive a piece of content from the user: ${content}

Your job:
1. Analyze the content scientifically and objectively.
2. Determine how likely the text was generated by AI.
3. Provide structured scoring, reasoning, and improvement suggestions.
4. Be honest—if the text strongly resembles AI-generated content, say so clearly.

Return the output only in JSON format at ${AIResponseFormat}, with no backticks, no extra text, and no commentary.

`;